/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Workpackage from './Workpackage';

/**
 * The Project model module.
 * @module model/Project
 * @version 1.0.0
 */
class Project {
    /**
     * Constructs a new <code>Project</code>.
     * @alias module:model/Project
     * @param projectName {String} 
     * @param projectDesc {String} 
     * @param projectWP {module:model/Workpackage} 
     */
    constructor(projectName, projectDesc, projectWP) { 
        
        Project.initialize(this, projectName, projectDesc, projectWP);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, projectName, projectDesc, projectWP) { 
        obj['projectName'] = projectName;
        obj['projectDesc'] = projectDesc;
        obj['projectWP'] = projectWP;
    }

    /**
     * Constructs a <code>Project</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Project} obj Optional instance to populate.
     * @return {module:model/Project} The populated <code>Project</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Project();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('projectName')) {
                obj['projectName'] = ApiClient.convertToType(data['projectName'], 'String');
            }
            if (data.hasOwnProperty('projectDesc')) {
                obj['projectDesc'] = ApiClient.convertToType(data['projectDesc'], 'String');
            }
            if (data.hasOwnProperty('projectWP')) {
                obj['projectWP'] = ApiClient.convertToType(data['projectWP'], Workpackage);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Project.prototype['_id'] = undefined;

/**
 * @member {String} projectName
 */
Project.prototype['projectName'] = undefined;

/**
 * @member {String} projectDesc
 */
Project.prototype['projectDesc'] = undefined;

/**
 * @member {module:model/Workpackage} projectWP
 */
Project.prototype['projectWP'] = undefined;






export default Project;

