/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Workpackage model module.
 * @module model/Workpackage
 * @version 1.0.0
 */
class Workpackage {
    /**
     * Constructs a new <code>Workpackage</code>.
     * @alias module:model/Workpackage
     * @param wpName {String} 
     * @param wpDesc {String} 
     */
    constructor(wpName, wpDesc) { 
        
        Workpackage.initialize(this, wpName, wpDesc);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, wpName, wpDesc) { 
        obj['wpName'] = wpName;
        obj['wpDesc'] = wpDesc;
    }

    /**
     * Constructs a <code>Workpackage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Workpackage} obj Optional instance to populate.
     * @return {module:model/Workpackage} The populated <code>Workpackage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Workpackage();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('wpName')) {
                obj['wpName'] = ApiClient.convertToType(data['wpName'], 'String');
            }
            if (data.hasOwnProperty('wpDesc')) {
                obj['wpDesc'] = ApiClient.convertToType(data['wpDesc'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Workpackage.prototype['_id'] = undefined;

/**
 * @member {String} wpName
 */
Workpackage.prototype['wpName'] = undefined;

/**
 * @member {String} wpDesc
 */
Workpackage.prototype['wpDesc'] = undefined;






export default Workpackage;

